
from agents import (
    facebook_draft_refine_agent,
    facebook_seo_compiler_agent
)
from crewai import Task

# Drafting and Refinement Task
drafting_refinement_task_facebook = Task(
    description=(
        "Generate and refine a draft for a Facebook post on {topic}. "
        "Create content that is informative, engaging, and aligns with current trends or developments in {topic}. "
        "Focus on enhancing grammar, clarity, and overall readability while ensuring alignment with the intended style and engagement goals. "
        "Include a mix of text and ideas for multimedia elements (like images, videos, or links) to enhance the post's engagement."
    ),
    expected_output=(
        "A compelling and polished draft Facebook post on {topic}, capturing the essence of {topic} and resonating with Facebook users. "
        "The draft should include suggestions  elements that support the content and enhance its appeal. "
        "The post should be improved in grammar, clarity, and readability, effectively communicating the intended message while maintaining a style that resonates with Facebook users."
    ),
    agent=facebook_draft_refine_agent,
)

# SEO Optimization and Content Compilation Task
seo_compilation_task_facebook = Task(
    description=(
        "Optimize a Facebook post on {topic} for discoverability and engagement. "
        "Identify and integrate relevant keywords and tags to improve visibility on Facebook's platform. "
        "Consider the use of effective SEO strategies to enhance the post's reach and engagement. "
        "Aggregate and compile the final results into a cohesive Facebook post, integrating content generated by drafting, refinement, and SEO optimization into a unified and engaging presentation."
    ),
    expected_output=(
        "A finalized Facebook post on {topic}, incorporating outputs from drafting, refinement, and SEO optimization. "
        "The post should be engaging and tailored to resonate with the target audience on Facebook. "
        "The post should be structured to maximize discoverability and engagement, appealing to the target audience effectively. "
        "End the post with a call-to-action inviting viewers to engage with the content, such as commenting, sharing"
    ),
    agent=facebook_seo_compiler_agent,
    async_execution=False,
    output_file="outputs/facebook/post.md"
)

