from crewai import Task
from .agents import (
    discord_drafting_agent,
    discord_refinement_agent,
    discord_seo_agent,
    discord_content_compiler,
    discord_formatting_agent
)

drafting_task_discord = Task(
    description=(
        "Generate a draft for a Discord post based on the topic {topic} and insights from the provided YouTube link {youtube_link}. "
        "Create content that is informative, engaging, and aligns with the interests of the Discord community. "
        "Include a mix of text and ideas for multimedia elements (like images, videos, or links) to enhance the post's engagement."
    ),
    expected_output=(
        "A compelling draft Discord post on {topic}, capturing the essence of the topic and insights from the YouTube video. "
        "The draft should include suggestions for multimedia elements that support the content and enhance its appeal."
    ),
    agent=discord_drafting_agent,
)

editing_task_discord = Task(
    description=(
        "Refine and polish a draft Discord post on {topic} based on insights from the provided YouTube link {youtube_link}. "
        "Focus on enhancing grammar, clarity, and overall readability while ensuring alignment with the intended style and engagement goals. "
        "Ensure the content is structured to maximize readability and interaction, and consider the inclusion of appropriate media."
    ),
    expected_output=(
        "A polished Discord post on {topic}, improved in grammar, clarity, and readability. "
        "The post effectively communicates the intended message while maintaining a style that resonates with the Discord community. "
        "The content should be engaging and ready for integration with multimedia elements."
    ),
    agent=discord_refinement_agent,
)

seo_task_discord = Task(
    description=(
        "Optimize a Discord post on {topic} for discoverability and engagement based on insights from the provided YouTube link {youtube_link}. "
        "Identify and integrate relevant keywords and tags to improve visibility on Discord's platform. "
        "Consider the use of effective SEO strategies to enhance the post's reach and engagement."
    ),
    expected_output=(
        "An optimized Discord post on {topic}, enhanced with relevant keywords and tags. "
        "The post is structured to maximize discoverability and engagement, appealing to the target audience effectively. "
        "Include the top 5 keywords and tags that best represent the content and attract the intended audience."
    ),
    agent=discord_seo_agent,
)

chief_task_discord = Task(
    description=(
        "Aggregate and compile the final results from various tasks into a cohesive Discord post. "
        "Integrate content generated by drafting, refinement, SEO optimization, and media selection into a unified and engaging presentation."
    ),
    expected_output=(
        "Str"
        "The generated content must be like a content creator advertising the youtube video {youtube_link}. "
        "A finalized Discord post on {topic}, incorporating outputs from drafting, refinement, SEO optimization. "
        "The post should be engaging, and tailored to resonate with the target audience on Discord. "
        "End the post with a call-to-action inviting viewers to engage with the content, such as commenting, sharing."
    ),
    agent=discord_content_compiler,
)

format_content_task_discord = Task(
    description=(
        "Format the Discord content in a professional and engaging manner, including the selected media. "
        "Ensure the post is well-structured, visually appealing, and optimized for readability and interaction. "
        "Format the content in Markdown, if applicable, and include the chosen media descriptions at the end of the post."

        """
        Example 1:
        🌟 Calling all RECians!🌟

        Welcome to the ultimate guide for Hackmaggedon 2024- Chapter 1, the biggest 24-hour hackathon at REC! Join us as we dive into everything you need to know to conquer Round 1.

        🎥In this video, we walk you through the essentials: from crafting the perfect PPT submission to understanding team rules and selecting the ideal problem statement.🤖

        Don't miss out! Registrations are now open and will close on July 14th. Gear up and get ready to unleash your creativity and innovation at Hackmaggedon 2024!🥳


        🔔 Subscribe for more updates and hit the notification bell to stay in the loop

        Example 2 :
        Hey there ✨
        Calling all coders! Doubt Clearing Session is HERE! 🚀

        We're thrilled to announce that you can now attend the Doubt Clearing Session, organized by the School of Computing and Information Science. 🎉

        We know you've been eagerly waiting to improve your coding skills, and that's why we prepared this session for your convenience.

        Learn from your peers: Get your doubts clarified by our speakers 🎓
        Keerthana M G
        Hursun SS
        Prajein CK
        Network with fellow coders: Connect with other attendees and discuss coding challenges. 🤝

        Get ready for the upcoming challenges: This session is a great way to prepare for future coding competitions. 💪

        Here's how to attend the Doubt Clearing Session:
        📅 Date: July 7, Sunday
        🕚 Time: 11 AM
        🌐 Platform: Google Meet
        

        Spread the word! Let your fellow RECians know that the Doubt Clearing Session is happening.

        For more details visit hackmageddon.in
        See you all there
        @everyone

"""
    ),
    agent=discord_formatting_agent,
    expected_output=(
        "The final output must be of one para with 4 to 5 lines that's all it must contain, it must be like content creator of the video {youtube_link} branding the video."
        "A well-formatted Discord post that is engaging and ready for publication. "
        "The content should be formatted in Markdown, ensuring it is visually appealing and easy to read."
        "Don't imitate the same response this is just for your reference be creative and customize your output accordingly"
        "Strictly don't relpicate the examples be creative and think"
    ),
    context=[chief_task_discord],
    async_execution=False,
    output_file="outputs/post.md"
)
